language: node_js
sudo: false

# https://docs.travis-ci.com/user/gui-and-headless-browsers/
# https://karma-runner.github.io/0.8/plus/Travis-CI.html

env:
  global:


#before_install:
#- npm install -g jspm
#- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
before_script:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 2 # give xvfb some time to start
#- npm run jspm-install
